[build]
command = "pip install -r requirements.txt && python app.py"
publish = "templates"
functions = "functions"

[build.environment]
PYTHON_VERSION = "3.9"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
